jakartaee/jaf-api

- pom.xml
Updated gpg plugin version to 1.6 (latest)
Remove unnecessary configuation.
> Update gpg version

- CONTRIBUTING.md
> #42: Update CONTRIBUTING.md for Specification Project's repositories

- activation/pom.xml
- pom.xml
> fix javadoc to contain speclicense

- spec/pom.xml
> fix target spec name

- CONTRIBUTING.md
- README.md
- spec/LICENSE.md
> Fix license related files

- activation/pom.xml
- activationapi/pom.xml
- demo/pom.xml
- pom.xml
- spec/pom.xml
> bump version to 2.0.1-SNAPSHOT

- activation/pom.xml
> fix the build by changing compilerArgs

- activation/pom.xml
- activationapi/pom.xml
- demo/pom.xml
- pom.xml
This is refactoring of the POM files in the project.
It's mainly about following changes:
- Maven plugins and dependencies upgrade
- Plugin default properties removal
- Use similar POM files pattern like other Jakarta projects
- Findbugs plugin replaced by Spotbugs plugin
Currently to simplify review process reformat is not applied.
Questions about JUnit dependency and maven-surefire-plugin. Are these components needed in the project? There are no any tests.
> [master] Maven build optimize

- activation/pom.xml
- activationapi/pom.xml
- demo/pom.xml
- pom.xml
> set version to 2.0.2-SNAPSHOT

- .github/workflows/maven.yml
- README.md
- api/pom.xml
- api/src/main/java/jakarta/activation/DataHandler.java
Added GitHub build job.
Updated README.
Fixed POM.
> Project cleanup.

- api/pom.xml
- api/src/main/java/jakarta/activation/ActivationDataFlavor.java
- api/src/main/java/jakarta/activation/CommandInfo.java
- api/src/main/java/jakarta/activation/CommandMap.java
- api/src/main/java/jakarta/activation/MailcapCommandMap.java
- api/src/main/java/jakarta/activation/MailcapRegistry.java
- api/src/main/java/jakarta/activation/MimeTypeParameterList.java
- api/src/main/java/jakarta/activation/MimetypesFileTypeMap.java
- api/src/main/java/jakarta/activation/SecuritySupport.java
> Fix compiler warnings

- spec/src/main/asciidoc/activation-spec.adoc
- spec/src/main/asciidoc/activation.adoc
- spec/src/main/asciidoc/license-efsl.adoc
> update cp years in spec,

- api/src/main/java/jakarta/activation/MailcapCommandMap.java
- api/src/main/java/jakarta/activation/MimetypesFileTypeMap.java
> fix cp year

- www/README.md
> remove duplicated note from the readme

- api/src/main/java/jakarta/activation/MailcapCommandMap.java
- api/src/main/java/jakarta/activation/MimetypesFileTypeMap.java
- www/README.md
> add info about 2.1.1 release

- .github/workflows/maven.yml
- api/src/main/java/jakarta/activation/FactoryFinder.java
> try api jar loader when loading a provider from the system property

- api/pom.xml
> update pointers in pom to the new location

- api/pom.xml
> update build plugins, remove unused ones

- api/pom.xml
> minor tweak to osgi requirements

- api/pom.xml
> fix version string

- www/README.md
> fix the release date

- .gitignore
- api/pom.xml
- api/src/main/java/jakarta/activation/FileDataSource.java
- api/src/main/java/jakarta/activation/FileTypeMap.java
- api/src/main/java/jakarta/activation/MimetypesFileTypeMap.java
- spec/src/main/asciidoc/activation.adoc
> Issue 124 add java nio path support

- api/src/main/java/jakarta/activation/ActivationDataFlavor.java
- api/src/main/java/jakarta/activation/CommandInfo.java
- api/src/main/java/jakarta/activation/CommandMap.java
- api/src/main/java/jakarta/activation/CommandObject.java
- api/src/main/java/jakarta/activation/DataContentHandler.java
- api/src/main/java/jakarta/activation/DataContentHandlerFactory.java
- api/src/main/java/jakarta/activation/DataHandler.java
- api/src/main/java/jakarta/activation/DataSource.java
- api/src/main/java/jakarta/activation/FactoryFinder.java
- api/src/main/java/jakarta/activation/FileDataSource.java
- api/src/main/java/jakarta/activation/FileTypeMap.java
- api/src/main/java/jakarta/activation/LogSupport.java
- api/src/main/java/jakarta/activation/MailcapCommandMap.java
- api/src/main/java/jakarta/activation/MailcapRegistry.java
- api/src/main/java/jakarta/activation/MimeType.java
- api/src/main/java/jakarta/activation/MimeTypeEntry.java
- api/src/main/java/jakarta/activation/MimeTypeParameterList.java
- api/src/main/java/jakarta/activation/MimeTypeParseException.java
- api/src/main/java/jakarta/activation/MimetypesFileTypeMap.java
- api/src/main/java/jakarta/activation/SecuritySupport.java
- api/src/main/java/jakarta/activation/ServiceLoaderUtil.java
- api/src/main/java/jakarta/activation/URLDataSource.java
- api/src/main/java/jakarta/activation/UnsupportedDataTypeException.java
- api/src/main/java/jakarta/activation/spi/MailcapRegistryProvider.java
- api/src/main/java/jakarta/activation/spi/MimeTypeRegistryProvider.java
- api/src/main/javadoc/doc-files/speclicense.html
* changes tabs to spaces through the repo to unify the formatting
* changes `@exception` to `@throws`
* fixes imports
* removes redundant modifiers
* uses java-style array declaration
> fix code formatting through the repo

- .github/workflows/maven.yml
- .github/workflows/web.yml
- api/pom.xml
> use 1.0.9 ee4j parent

- api/pom.xml
should keep the version number as 2.1.x
> 2.1.3 release
